workshop_path: C:\Users\miyum\Downloads\ARC380\arc380_s26_fork\arc380_s26\workshops
max_height: 5
link_name_sim: "gripper_tcp"
link_name_real: "gripper_tcp_calibrated"
gripper_open: 0.0
gripper_closed: 0.01

colors_r: [0, 205, 91, 151, 0]
colors_g: [28, 180, 128, 45, 98]
colors_b: [61, 144, 129, 0, 159]

offset_x: 0.0 #to fix 
offset_y: 0.0 #to fix

base_block_locations: C:\Users\miyum\Downloads\ARC380\arc380_s26_fork\arc380_s26\workshops\final_project\base_block_locations.csv