ros2_control:
  ros__parameters:
    update_rate: 250  # Hz

    hardware:
      plugin: gz_ros2_control/GazeboSimSystem

    joints:
      - name: joint_1
        command_interfaces: [position]
        state_interfaces: [position, velocity]
      - name: joint_2
        command_interfaces: [position]
        state_interfaces: [position, velocity]
      - name: joint_3
        command_interfaces: [position]
        state_interfaces: [position, velocity]
      - name: joint_4
        command_interfaces: [position]
        state_interfaces: [position, velocity]
      - name: joint_5
        command_interfaces: [position]
        state_interfaces: [position, velocity]
      - name: joint_6
        command_interfaces: [position]
        state_interfaces: [position, velocity]
      - name: left_finger_joint
        command_interfaces: [position]
        state_interfaces: [position, velocity]
      - name: right_finger_joint
        command_interfaces: [position]
        state_interfaces: [position, velocity]